main: it.escanortargaryen.simpledeathswap.SimpleDeathSwap

name: ${project.name}
description: A plugin for a game called Death Swap
version: ${project.version}
author: [ EscanorTargaryen ]

api-version: 1.13

permissions:
  simpledeathswap:
    default: true
    description: permission to use /simpledeathswap
  simpledeathswap.gamestart:
    default: op
    description: permission to start a game
  simpledeathswap.stopgame:
    default: true
    description: permission to stop a game. Only the owner can disband the game